language: python
python:
  - "3.5"
before_install:
    - sudo apt-get update
    - sudo apt-get install -y python-opencv
    - export PYTHONPATH=$PYTHONPATH:/usr/lib/pymodules/python3.5
install:
  - pip install -r requirements.txt
script:
  - python -c "import numpy; import cv2"
