language: python
python:
  - "3.5"
  - "3.6"
before_install:
    - sudo apt-get update
    - sudo apt-get install -y python-opencv
install:
  - pip install -r requirements.txt
script:
  - python -c "import numpy; import cv2"
